---
site_name: Pulp OCI Images
site_description: Pulp Single Container
site_author: Pulp Team
site_url: https://docs.pulpproject.org/pulp_oci_images/
repo_name: pulp/pulp-oci-images
repo_url: https://github.com/pulp/pulp-oci-images
edit_uri: edit/main/docs
theme:
  features:
    - search.suggest
    - search.highlight
    - search.share
  name: material
  logo: images/pulp_logo_big.png
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
  - Home: index.md
  - Changelog: CHANGES.md
markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.superfences
  - admonition
extra:
  version:
    provider: mike
    default: latest
plugins:
  - git-revision-date
  - search:
      lang: en
      prebuild_index: true
